import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./src/components/Header";
import ClientReduxProvider from "./src/components/ClientReduxProvider";
import Sidebar from "./src/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientReduxProvider>
          <Header />
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </ClientReduxProvider>
      </body>
    </html>
  );
}
